- fa: "building"
  content: "GraphQL, REST, Firebase"
- fa: "keyboard"
  content: "Postgres, Firestore"
- fa: "store"
  content: "React, Angular, Ember"
- fa: "wrench"
  content: "Node.js, Spring, Hibernate"
